### ISSUE TITLE
Compile instructions for ARM

### ISSUE THREAD

**Issue by G33kDude** [derf/wii-sensors#2]
I'm trying to get your wiispkr program to compile on an ARM based system, similar to an average raspberry pi. The biggest problem so far has been hunting dependencies, and I'm not sure all of them have ARM ports readily available (though source seems to be available so far). I'm no C programmer, so getting all the parts to fit together and compile is somewhat difficult for me without help. Would you be able to put together a guide for compiling on ARM?

**Comment by derf** [comment]
Unfortunately no. While I do have access to a few ARM devices, I don't have the spare time to do that (and don't do active work on this project anymore).

I assume the biggest issue will be libwiimote. If I didn't miss anything its latest release is from 2007, so it should be very compatibly with my wiispkr code, but I don't even know if the bluetooth API it uses is still supported by modern linux systems. If it is it's a rather simple matter of compiling libwiimote and then wiispkr (it _should_ just work on ARM) — Otherwise you'll have to either patch libwiimote to use a new API or wiispkr to use a different wiimote library. I'll gladly answer questions you have about the wiispkr code, but that's about all I can do. Sorry.

**Comment by G33kDude** [comment]
Ok, thanks anyways. Do you think python would be up to the challenge of generating this real time byte stream?

**Comment by derf** [comment]
It should be, yeah. Plus, you could use the cwiid module, which seems to be more up-to-date anyways :)

**Comment by G33kDude** [comment]
I got it working, though it definitely sounds 8-bit, and I don't think it's playing at full speed. I had a short delay in there to get it roughly to 10ms, but I think it takes more than 10ms per iteration already (though I didn't actually measure)

```
#!/usr/bin/python

import cwiid

volume = "\x60"
rate = "\x70\x17" # 2kHz, 12000000/2000 in little-endian

pcm8bit = "\x40"
config = "\x00" + pcm8bit + rate + volume + "\x00\x00"

print "Sync wiimote now"
wm = cwiid.Wiimote()
wm.led = 6

# Initialization sequence
wm.send_rpt(0, 0x14, "\x04") # Enable speaker
wm.send_rpt(0, 0x19, "\x04") # Mute speaker
wm.write(0x04, 0xa20001, config) # It throws an exception if I put this after \x08
wm.write(0x04, 0xa20009, "\x01")
wm.write(0x04, 0xa20001, "\x08")
wm.write(0x04, 0xa20008, "\x01")
wm.send_rpt(0, 0x19, "\x00") # Unmute speaker

size = chr(20 << 3)
with open("wiiplay.raw", "r") as f:
	while True:
		sound = f.read(20)
		if len(sound) < 20:
			raise EOFError
		wm.send_rpt(0, 0x18, size + sound)
```

**Comment by G33kDude** [comment]
I'm partway through a C reimplementaion, and am questioning some comments made at the top of your c file. Specifically, "The speaker eats up to 20 bytes of raw data at once, so this gives us 100 updates per second (one every 10 us)." Shouldn't that say milliseconds (ms), not microseconds (us)?

**Comment by derf** [comment]
nice!

Yeah, the comment is wrong. The code actually sleeps for 1ms between each bluetooth packet, and I think data is transferred at a rate of one packet per 10ms (since communication also takes a while, though I'm not sure if it really is ~9ms). At least 10ms make a lot of sense for 2kHz data in 20B chunks.

**Comment by G33kDude** [comment]
I think I have all my code written correctly, but for some reason it still just won't "work". If I hold the wiimote right up against my ear I can faintly hear what sounds like a bad rendition of the already bad audio, but other than that it just doesn't work. Also, sorry for the excessive headers and inconsistent formatting, I haven't used C before and don't really know much about what I'm doing.

```
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <string.h>
#include <sys/stat.h>
#include <sys/time.h>
#include <sys/types.h>
#include <time.h>
#include <fcntl.h>
#include <math.h>

#include <bluetooth/bluetooth.h>
#include <cwiid.h>

#define SPK_REG_CFG  0x04a20001
#define SPK_REG_VOL  0x04a20005
#define SPK_REG_FREQ 0x04a20004

#define PCM8BIT 0x40

int write_byte(cwiid_wiimote_t *wm, uint8_t flags, uint32_t offset, uint8_t data)
{
    return cwiid_write(wm, flags, offset, sizeof(data), &data);
}

int report_byte(cwiid_wiimote_t *wm, uint8_t flags, uint8_t report, uint8_t data) {
    return cwiid_send_rpt(wm, flags, report, sizeof(data), &data);
}

int main(int argc, char **argv)
{
    bdaddr_t bdaddr = *BDADDR_ANY;
    cwiid_wiimote_t * wm = NULL;

    int readbytes;

    struct timeval tv;
    uint32_t timeout = 0;
    uint32_t t, start;

    uint8_t wmvolume = 0x40;
    uint16_t rate = 12000000 / 2000; // 2kHz

    struct {
        uint8_t size;
        uint8_t data[20];
    } spkr_data;

    spkr_data.size = 20;

    if (argc >= 2)
        wmvolume = atoi(argv[1]);

    /* see http://wiibrew.org/wiki/Wiimote#Speaker_Configuration */
    uint8_t spk_config[] = {
        0x00, PCM8BIT,
        rate & 0xFF, rate>>8 & 0xFF,
        wmvolume, 0x00, 0x00
    };

    puts("Sync wiimote now");

    wm = cwiid_open(&bdaddr, 0);
    if (!wm) {
        fprintf(stderr, "unable to open wiimote");
        exit(1);
    }

    puts("connected");
    cwiid_set_led(wm, 0b0110);

    report_byte(wm, 0x00, 0x14, 0x04); // Enable speaker
    report_byte(wm, 0x00, 0x19, 0x04); // Mute speaker

    cwiid_write(wm, CWIID_RW_REG, 0xa20001, sizeof(spk_config), &spk_config);

    write_byte(wm, CWIID_RW_REG, 0xa20009, 0x01);
    write_byte(wm, CWIID_RW_REG, 0xa20001, 0x08);
    write_byte(wm, CWIID_RW_REG, 0xa20008, 0x01);

    report_byte(wm, 0x00, 0x19, 0x00); // Unmute speaker

    while (1) {
        readbytes = read(0, &spkr_data.data, sizeof(spkr_data.data));
        if (readbytes < 1) {
            return 0;
        }

        // int i;
        // for (i=0; i<20; i++) {
            // printf("\\x%02x", spkr_data.data[i]);
        // }
        // printf("\n");
        // fflush(stdout);

        cwiid_send_rpt(wm, 0, 0x18, sizeof(spkr_data), &spkr_data);
        usleep(1000);
    }

    return 0;
}
```

**Comment by G33kDude** [comment]
Ah! Solved my issue. I forgot to shift `spkr_data.size` left 3 bits. I'd say I have this working well enough to close the issue. Thanks for your help!
